---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argo-server
  annotations:
    ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/backend-protocol: https # ingress-nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: flask-service
              servicePort: 5000
          - backend:
              serviceName: argo-server
              servicePort: 2746
            #path: /argo(/|$)(.*)
            path: /
